name: PaystackJavaClient Maven CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Step 1 - Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Step 2 - Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Step 3 - Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Step 4 - Build Project with Maven
        run: mvn -B package --file pom.xml

      - name: Step 5 - Configure Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GH_PAT }}"
            }]

      - name: Step 5.1 - Read POM.xml Version
        if: contains(env.PUSH_PACKAGES, true)
        run: chmod +x read-version.sh && ./read-version.sh

      - name: Step 6 - Release Parent
        if: contains(env.PUSH_PACKAGES, true)
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        uses: qcastel/github-actions-maven-release@master
        with:
          skip-perform: true
          release-branch-name: "main"
          git-release-bot-name: "ReleaseBot"
          m2-home-folder: '~/.m2/repository'
          access-token: ${{ secrets.GH_PAT }}
          maven-args: "-Dmaven.resolver.transport=wagon -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"

      - name: Step 7 - Publish Domain Package
        if: contains(env.PUSH_PACKAGES, true)
        run: mvn -Drevision=${{ env.RELEASE_VERSION }} -B deploy -pl paystack-domain
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Step 8 - Publish Client Package
        if: contains(env.PUSH_PACKAGES, true)
        run: mvn -Drevision=${{ env.RELEASE_VERSION }} -B deploy -pl paystack-clients
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
