name: PaystackJavaClient Maven CD

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Configure Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GH_PAT }}"
            }]

      - name: Publish Domain Package
        run: mvn -B deploy -pl paystack-domain
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Publish Client Package
        run: mvn -B deploy -pl paystack-clients
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}