name: PaystackJavaClient Maven CD

on:
  repository_dispatch:
    types: [execute-publish]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Configure Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GH_PAT }}"
            }]

      - name: Publish Domain Package
        run: mvn versions:set -DnewVersion=${{ github.event.client_payload.version }} -B deploy --file paystack-domain/release-pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Publish Client Package
        run: mvn versions:set -DnewVersion=${{ github.event.client_payload.version }} -B deploy --file paystack-clients/release-pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}